version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: TempSelenium
    shm_size: 2g
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    networks:
      - default

  librizz:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: librizz:2.0
    container_name: LibRizz
    shm_size: 2g
    depends_on:
      - selenium
    networks:
      - default

networks:
  default:
    driver: bridge
